version = 1

exclude_patterns = [
  "test ",
  "tests "
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

[[transformers]]
name = "black"

[[transformers]]
name = "prettier"